### ISSUE TITLE
Tag(s) to be analyzed should be configurable 

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/SOCommentEditsMapping#10]
Ideally, allow the user to decide on which tags they want to run the analysis on (rather than have the five we used hard coded in the code)

**Comment by Hk-tang** [comment]
The `tags.cfg` file was originally to be for what tags to run the analysis on, so I may be able to incorporate it somehow into the analysis. However, `tags.cfg` is used currently to split the `results.csv` into the specified tags. e.g., we run the analysis on all 5 tags and the program ouputs a `results.csv` that includes all the results. There is a part of the program that will split the `results.csv` into the tags mentioned in the `tags.cfg`, so if we specify `<java>` and `<javascript>` in `tags.cfg` the program will create a `results_<tag>.csv` containing all **matched** pairs of that tag, but only for the specified tags. So in this case will generate a `results_java.csv` and `results_javascript.csv` but will not create a tag specific csv for the other 3 tags
