### ISSUE TITLE
Extract code pairs

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/SOCommentEditsMapping#11]
To package the results in a usable way, we should have a format to store the before/after versions of the code snippet of the confirmed pair along with the comment. It should also include the question ID, answer ID, comment ID, and edit ID for traceability. Some automatically processable format such as json or yml can be used. Each pair can be an entry (if json) or a file (if yml -- not sure how pretty yml's multiple entries would work to put everything in a single file). Since the code snippets are typically small, we can have a single file representing each pair (i.e., the code snippets are directly available in the entry).

So given a csv of confirmed pairs, we should have a script that generates the concrete data set rather than have people need to query the DB themselves.

**Comment by Hk-tang** [comment]
I decided to use JSON instead of yml, as such all pairs will be their own JSON object in a single file. Along with the mentioned properties of QuestionId, AnswerId, CommentId, EditId, Before & After snapshots of the edit, and the comment, we will add the optional values of Confirmed, Useful, Tangled, Category, Tags

**Comment by Hk-tang** [comment]
I made the packaging occur in both the full analysis and when separately triggered by an argument. If we shouldn't package into json automatically I can remove it and only have it occur if explicitly asked by the user

**Comment by snadi** [comment]
No, I think that makes sense. We should always produce the json pair data or if someone has results from a previous run, they can trigger only a conversion by the arguments.

Do you already have an example of the pair? I imagine some of them might be tricky to get (e.g., entries with multiple code entries) and would need clever workarounds/heuristics
