### ISSUE TITLE
Clarifications in json pair documentation

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/SOCommentEditsMapping#20]
I finally went through the wiki documentation for the new json output:

- I elaborated on the descriptions of useful, confirmed etc. Please double check that what I changed is correct
- Can you add an example and description of "categories" .. probably not clear to someone who didn't read the paper so make a relationship
- "Before and After are both lists in the event that there are multiple relevant code snippets that changed." Can you elaborate a bit or paraphrase? Currently, confusing. In general, this whole paragraph is confusing. Try to add some punctuation so the meaning is clear. (please also add necessary commas to the paragraph after)
- In the ReadMe, "general_precision_confirmed_results.json is the json of only confirmed pairs of the subset of all five tags that we used to calculate the general precision of the program." --> so this means that no entry will have confirmed as 0? I mean what happens to ones we reviewed and marked as false positives (I guess this goes back to the elaborations I added, which may be incorrect)

**Comment by Hk-tang** [comment]
I updated the wiki page to address what you mentioned. And yes right now the JSON only has confirmed at 1, there is no confirmed 0. I can change the JSON to include confirmed: 0, if that is wanted

**Comment by snadi** [comment]
@Hk-tang for the confirmed sheet, I think we should have all those reviewed and indicate whether they were marked as 0 or 1 (this avoids someone else replicating the effort and also allows others to see what we marked as 0). Perhaps the sheet should be called `reviewed_comment_edit_pairs.json` so the name matches the content? What do you think?

**Comment by Hk-tang** [comment]
I think that is good. I will make those changes.

**Comment by snadi** [comment]
@Hk-tang is this already addressed? Should we close it?

**Comment by Hk-tang** [comment]
JSON updated in this commit 26a668716dd114e975aacea35a5d9a551d98057f
