### ISSUE TITLE
Querry

### ISSUE THREAD

**Issue by Manas-Embold** [ualberta-smr/SOCommentEditsMapping#24]
Hi Team,
Thank you for sharing wonderful work.

I had a question.
So we can generate **"results.csv"** (contains a row for each comment in the data set and the matching edit).
Now next you mentioned you utilized these edit pairs to recommend changes through pull requests for 15 github repos.
Have you also shared code for recommending those changes to those 15 repos or were those recommendations done manually.

**Comment by Manas-Embold** [comment]
@Hk-tang  / @snadi 
Can someone help ?

**Comment by Hk-tang** [comment]
Hello, from the "results.csv" file, we manually selected 15 rows from the file and manually found the repos and make changes. The recommendations are not yet automated.

**Comment by junkgear** [comment]
Alright.
Thanks much!
